server:
  port: 9191

spring:
  application:
    name: API-GATEWAY

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

studentservice:
  url: http://localhost:9001/students
courseservice:
  url: http://localhost:9002/courses