server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  main:
    allow-bean-definition-overriding: true

student-service:
  url: http://localhost:9001/students
course-service:
  url: http://localhost:9002/courses